name: Free Disk Space
description: Free runner disk space by removing unused Docker images

inputs:
  docker-images:
    description: "Remove Docker images"
    required: false
    default: "true"
  android:
    description: "Remove Android runtime"
    required: false
    default: "false"
  dotnet:
    description: "Remove .NET runtime"
    required: false
    default: "false"
  haskell:
    description: "Remove Haskell runtime"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: ${{ inputs.android }}
        dotnet: ${{ inputs.dotnet }}
        haskell: ${{ inputs.haskell }}
        large-packages: false
        docker-images: ${{ inputs.docker-images }}
        swap-storage: false
