name: Publish Websocket Mock Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - tools/websocket-mock/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/levity-websocket-mock

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Get current date
        id: date
        run: echo "today=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build AMD64
        working-directory: tools/websocket-mock
        run: cross build --release --target x86_64-unknown-linux-musl

      - name: Build ARM64
        working-directory: tools/websocket-mock
        run: cross build --release --target aarch64-unknown-linux-musl

      - name: Prepare Outputs
        run: |
          mkdir -p tools/websocket-mock/output/amd64 tools/websocket-mock/output/arm64
          cp tools/websocket-mock/target/x86_64-unknown-linux-musl/release/websocket-mock tools/websocket-mock/output/amd64/
          cp tools/websocket-mock/target/aarch64-unknown-linux-musl/release/websocket-mock tools/websocket-mock/output/arm64/

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.date.outputs.today }}
            type=sha,format=long

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: tools/websocket-mock
          file: tools/websocket-mock/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
